excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://blairjohnson.github.io
title: Blair Johnson
tagline: Mirror, Mirror on the wall: Who am I?
description: Even less than what I would be willing to share.
paginate: 9